const menuButton=document.querySelector('.menu');
const siteNav=document.querySelector('#site-nav');
function closeMobileMenu(){if(!siteNav||!menuButton)return;siteNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Open menu')}
if(menuButton&&siteNav){menuButton.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Close menu':'Open menu')});siteNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMobileMenu));window.addEventListener('resize',()=>{if(window.innerWidth>800)closeMobileMenu()})}
const configured=Boolean(window.LEXCESS_SUPABASE_URL&&window.LEXCESS_SUPABASE_ANON_KEY);const db=configured?supabase.createClient(window.LEXCESS_SUPABASE_URL,window.LEXCESS_SUPABASE_ANON_KEY):null;
const demoProducts=[{name:'African Print Midi Dress',category:'Dresses',price:320,description:'Elegant statement piece.'},{name:'Classic Polo Shirt',category:'Men',price:180,description:'Clean everyday style.'},{name:'Cargo Shorts',category:'Shorts',price:160,description:'Easy, confident fit.'}];
let allProducts=[];
function money(v){return `GH₵ ${Number(v||0).toLocaleString()}`}
function imagesFor(v){if(!v)return[];try{const a=JSON.parse(v);if(Array.isArray(a))return a.filter(Boolean)}catch{}return[String(v)]}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s)}
function renderProducts(items){const el=document.querySelector('#products');document.querySelector('#product-count').textContent=`${items.length} ${items.length===1?'item':'items'}`;el.innerHTML=items.length?items.map((p,i)=>{const imgs=imagesFor(p.image_url);const media=imgs.length?`<div class="product-image has-photo"><img src="${escapeAttr(imgs[0])}" alt="${escapeAttr(p.name||'Lexcess item')}">${imgs.length>1?`<span class="photo-count">${imgs.length} photos</span>`:''}</div>`:`<div class="product-image">LEXCESS</div>`;return `<article class="product" data-product-index="${i}" tabindex="0" role="button" aria-label="Get ${escapeAttr(p.name||'this item')}">${media}<div class="product-info"><div class="eyebrow">${escapeHtml(p.category||'COLLECTION')}</div><h3>${escapeHtml(p.name||'Lexcess item')}</h3><p>${escapeHtml(p.description||'Tap to request this item.')}</p><span class="price">${money(p.price)}</span></div></article>`}).join(''):`<div class="empty">The next drop is coming soon.</div>`;window.__lexcessProducts=items;el.querySelectorAll('.product').forEach(card=>{const open=()=>{const index=Number(card.dataset.productIndex);const p=window.__lexcessProducts?.[index];const imgs=imagesFor(p?.image_url);if(imgs.length)openGallery(index);else openOrder(index)};card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function openOrder(index){const p=window.__lexcessProducts?.[index];if(!p)return;const imgs=imagesFor(p.image_url);let modal=document.getElementById('order-modal');if(!modal){modal=document.createElement('div');modal.id='order-modal';modal.className='order-modal';modal.innerHTML='<div class="order-backdrop"></div><div class="order-card" role="dialog" aria-modal="true" aria-labelledby="order-title"><div class="order-head"><div><p class="eyebrow">REQUEST THIS ITEM</p><h3 id="order-title"></h3><p>Send your details and we will contact you to arrange getting it.</p></div><button class="order-close" type="button" aria-label="Close">×</button></div><div class="order-summary"><img id="order-image" alt=""><div><strong id="order-name"></strong><span id="order-price"></span><p id="order-category"></p></div></div><form id="order-form" class="order-form"><input type="hidden" name="item"><input type="hidden" name="price"><label>Full name *<input name="name" required placeholder="Your name"></label><label>Phone / WhatsApp *<input name="phone" required placeholder="Your number"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Size<input name="size" placeholder="e.g. M, L, XL or N/A"></label><label>Quantity<input name="quantity" type="number" min="1" value="1"></label><label>Preferred contact<select name="contact"><option>WhatsApp</option><option>Phone call</option><option>Email</option></select></label><label class="full">Anything else?<textarea name="notes" placeholder="Colour, delivery area, fitting request, etc."></textarea></label><button class="btn" type="submit">Request this item →</button><p class="form-msg full" id="order-msg"></p></form></div>';document.body.appendChild(modal);modal.querySelector('.order-backdrop').onclick=closeOrder;modal.querySelector('.order-close').onclick=closeOrder;modal.querySelector('#order-form').addEventListener('submit',submitOrder)}modal.style.display='flex';document.getElementById('order-name').textContent=p.name||'Lexcess item';document.getElementById('order-price').textContent=money(p.price);document.getElementById('order-category').textContent=p.category||'Collection';const img=document.getElementById('order-image');if(imgs.length){img.src=imgs[0];img.style.display='block'}else img.style.display='none';const form=document.getElementById('order-form');form.item.value=p.name||'';form.price.value=money(p.price);form.dataset.productId=p.id||'';form.reset();form.item.value=p.name||'';form.price.value=money(p.price);document.getElementById('order-msg').textContent='';document.body.style.overflow='hidden'}
function closeOrder(){const m=document.getElementById('order-modal');if(m)m.style.display='none';document.body.style.overflow=''}
async function submitOrder(e){e.preventDefault();const form=e.currentTarget,msg=document.getElementById('order-msg');const values=Object.fromEntries(new FormData(form).entries());const text=`Item request: ${values.item}\nPrice shown: ${values.price}\nSize: ${values.size||'N/A'}\nQuantity: ${values.quantity||1}\nPreferred contact: ${values.contact}\nPhone: ${values.phone}\nNotes: ${values.notes||'None'}`;if(!db){msg.textContent='Connect Supabase to activate item requests.';return}const {error}=await db.from('messages').insert({name:values.name,email:values.email||'',message:text});msg.textContent=error?'Something went wrong. Please try again.':'Request sent — we will contact you shortly.';if(!error){form.reset();form.item.value=values.item;form.price.value=values.price}}
let galleryIndex=0,galleryPhoto=0;
function openGallery(index){const p=window.__lexcessProducts?.[index];if(!p)return;const imgs=imagesFor(p.image_url);if(!imgs.length)return;galleryIndex=index;galleryPhoto=0;let modal=document.getElementById('photo-gallery');if(!modal){modal=document.createElement('div');modal.id='photo-gallery';modal.innerHTML='<div class="gallery-backdrop"></div><div class="gallery-panel"><button class="gallery-close" aria-label="Close">×</button><button class="gallery-prev" aria-label="Previous photo">‹</button><img id="gallery-main" alt=""><button class="gallery-next" aria-label="Next photo">›</button><div id="gallery-caption"></div><div id="gallery-thumbs"></div><button id="gallery-request" class="btn gallery-request" type="button">Get This Item →</button></div>';document.body.appendChild(modal);modal.querySelector('.gallery-backdrop').onclick=closeGallery;modal.querySelector('.gallery-close').onclick=closeGallery;modal.querySelector('.gallery-prev').onclick=()=>moveGallery(-1);modal.querySelector('.gallery-next').onclick=()=>moveGallery(1);modal.querySelector('#gallery-request').onclick=()=>{closeGallery();openOrder(galleryIndex)};let touchStartX=0;const main=modal.querySelector('#gallery-main');main.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0].clientX},{passive:true});main.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStartX;if(Math.abs(dx)>45)moveGallery(dx<0?1:-1)},{passive:true})}modal.style.display='grid';renderGallery()}
function renderGallery(){const p=window.__lexcessProducts?.[galleryIndex],imgs=imagesFor(p?.image_url);if(!p||!imgs.length)return;galleryPhoto=Math.max(0,Math.min(galleryPhoto,imgs.length-1));document.getElementById('gallery-main').src=imgs[galleryPhoto];document.getElementById('gallery-main').alt=p.name||'Lexcess item';document.getElementById('gallery-caption').textContent=`${p.name||'Item'} · ${galleryPhoto+1} of ${imgs.length}`;document.getElementById('gallery-thumbs').innerHTML=imgs.map((u,i)=>`<button class="gallery-thumb ${i===galleryPhoto?'active':''}" data-i="${i}"><img src="${escapeAttr(u)}" alt="Photo ${i+1}"></button>`).join('');document.querySelectorAll('.gallery-thumb').forEach(b=>b.onclick=()=>{galleryPhoto=Number(b.dataset.i);renderGallery()});document.querySelector('.gallery-prev').style.display=imgs.length>1?'block':'none';document.querySelector('.gallery-next').style.display=imgs.length>1?'block':'none'}
function moveGallery(dir){const imgs=imagesFor(window.__lexcessProducts?.[galleryIndex]?.image_url);if(imgs.length<2)return;galleryPhoto=(galleryPhoto+dir+imgs.length)%imgs.length;renderGallery()}
function closeGallery(){const m=document.getElementById('photo-gallery');if(m)m.style.display='none'}
async function loadProducts(){if(!db){allProducts=demoProducts;renderProducts(allProducts);return}const {data,error}=await db.from('products').select('*').eq('published',true).order('created_at',{ascending:false});allProducts=error?[]:(data||[]);renderProducts(allProducts)}
function filterProducts(category){const items=category==='All'?allProducts:allProducts.filter(p=>String(p.category||'').toLowerCase()===category.toLowerCase());renderProducts(items)}
async function submitForm(form,table,msgId){const msg=document.getElementById(msgId);const values=Object.fromEntries(new FormData(form).entries());if(!db){msg.textContent='Connect Supabase to activate online submissions.';return}const {error}=await db.from(table).insert(values);msg.textContent=error?'Something went wrong. Please try again.':'Sent successfully — we will be in touch.';if(!error)form.reset()}
document.querySelectorAll('.category-strip a').forEach(a=>a.addEventListener('click',()=>filterProducts(a.dataset.filter)));document.getElementById('booking-form').addEventListener('submit',e=>{e.preventDefault();submitForm(e.currentTarget,'bookings','booking-msg')});document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();submitForm(e.currentTarget,'messages','contact-msg')});loadProducts();
document.addEventListener('keydown',e=>{const m=document.getElementById('photo-gallery');if(m&&m.style.display!=='none'){if(e.key==='Escape')closeGallery();if(e.key==='ArrowLeft')moveGallery(-1);if(e.key==='ArrowRight')moveGallery(1)}});
