const configured=Boolean(window.LEXCESS_SUPABASE_URL&&window.LEXCESS_SUPABASE_ANON_KEY);const db=configured?supabase.createClient(window.LEXCESS_SUPABASE_URL,window.LEXCESS_SUPABASE_ANON_KEY):null;
const demoProducts=[{name:'After Hours Dress',category:'Dresses',price:850,description:'A sculpted statement silhouette.'},{name:'Lime Theory Set',category:'Sets',price:720,description:'Sharp, playful and built for movement.'},{name:'Noir Column Dress',category:'Dresses',price:980,description:'Minimal lines with maximum presence.'}];
function money(v){return `GH₵ ${Number(v||0).toLocaleString()}`}
function imagesFor(v){if(!v)return[];try{const a=JSON.parse(v);if(Array.isArray(a))return a.filter(Boolean)}catch{}return[String(v)]}
function renderProducts(items){const el=document.querySelector('#products');document.querySelector('#product-count').textContent=`${items.length} pieces`;el.innerHTML=items.length?items.map((p,i)=>{const imgs=imagesFor(p.image_url);const media=imgs.length?`<div class="product-image has-photo" data-product-index="${i}"><img src="${escapeAttr(imgs[0])}" alt="${escapeAttr(p.name||'Lexcess dress')}">${imgs.length>1?`<span class="photo-count">${imgs.length} photos · click to view</span>`:''}</div>`:`<div class="product-image">LEXCESS</div>`;return `<article class="product" data-product-index="${i}">${media}<div class="product-info"><div class="eyebrow">${escapeHtml(p.category||'COLLECTION')}</div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'')}</p><span class="price">${money(p.price)}</span></div></article>`}).join(''):`<div class="empty">The next drop is coming soon.</div>`;window.__lexcessProducts=items;document.querySelectorAll('[data-product-index]').forEach(el=>el.addEventListener('click',()=>openGallery(Number(el.dataset.productIndex))))}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s)}
let galleryIndex=0,galleryPhoto=0;
function openGallery(index){const p=window.__lexcessProducts?.[index];if(!p)return;const imgs=imagesFor(p.image_url);if(!imgs.length)return;galleryIndex=index;galleryPhoto=0;let modal=document.getElementById('photo-gallery');if(!modal){modal=document.createElement('div');modal.id='photo-gallery';modal.innerHTML='<div class="gallery-backdrop"></div><div class="gallery-panel"><button class="gallery-close" aria-label="Close">×</button><button class="gallery-prev" aria-label="Previous">‹</button><img id="gallery-main" alt=""><button class="gallery-next" aria-label="Next">›</button><div id="gallery-caption"></div><div id="gallery-thumbs"></div></div>';document.body.appendChild(modal);modal.querySelector('.gallery-backdrop').onclick=closeGallery;modal.querySelector('.gallery-close').onclick=closeGallery;modal.querySelector('.gallery-prev').onclick=()=>moveGallery(-1);modal.querySelector('.gallery-next').onclick=()=>moveGallery(1);document.addEventListener('keydown',galleryKeys)}modal.style.display='grid';renderGallery()}
function renderGallery(){const p=window.__lexcessProducts?.[galleryIndex],imgs=imagesFor(p?.image_url);if(!p||!imgs.length)return;galleryPhoto=Math.max(0,Math.min(galleryPhoto,imgs.length-1));document.getElementById('gallery-main').src=imgs[galleryPhoto];document.getElementById('gallery-main').alt=p.name||'Lexcess dress';document.getElementById('gallery-caption').textContent=`${p.name||'Dress'} · ${galleryPhoto+1} of ${imgs.length}`;document.getElementById('gallery-thumbs').innerHTML=imgs.map((u,i)=>`<button class="gallery-thumb ${i===galleryPhoto?'active':''}" data-i="${i}"><img src="${escapeAttr(u)}" alt="Photo ${i+1}"></button>`).join('');document.querySelectorAll('.gallery-thumb').forEach(b=>b.onclick=()=>{galleryPhoto=Number(b.dataset.i);renderGallery()});document.querySelector('.gallery-prev').style.display=imgs.length>1?'block':'none';document.querySelector('.gallery-next').style.display=imgs.length>1?'block':'none'}
function moveGallery(dir){const imgs=imagesFor(window.__lexcessProducts?.[galleryIndex]?.image_url);if(imgs.length<2)return;galleryPhoto=(galleryPhoto+dir+imgs.length)%imgs.length;renderGallery()}
function closeGallery(){const m=document.getElementById('photo-gallery');if(m)m.style.display='none'}
function galleryKeys(e){const m=document.getElementById('photo-gallery');if(!m||m.style.display==='none')return;if(e.key==='Escape')closeGallery();if(e.key==='ArrowLeft')moveGallery(-1);if(e.key==='ArrowRight')moveGallery(1)}
async function loadProducts(){if(!db){renderProducts(demoProducts);return}const {data,error}=await db.from('products').select('*').eq('published',true).order('created_at',{ascending:false});renderProducts(error?[]:data||[])}
async function submitForm(form,table,msgId){const msg=document.getElementById(msgId);const values=Object.fromEntries(new FormData(form).entries());if(!db){msg.textContent='Connect Supabase to activate online submissions.';return}const {error}=await db.from(table).insert(values);msg.textContent=error?'Something went wrong. Please try again.':'Sent successfully — we will be in touch.';if(!error)form.reset()}
document.getElementById('booking-form').addEventListener('submit',e=>{e.preventDefault();submitForm(e.currentTarget,'bookings','booking-msg')});document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();submitForm(e.currentTarget,'messages','contact-msg')});loadProducts();
